version: 0.2
phases:
  build:
    commands:
     # - make test # temp commented out while pipline is developed
      - make docker-build
      - docker save -o docker.tar container-release:local
artifacts:
  files:
    - docker.tar

