version: 0.2
phases:
  build:
    commands:
      # - make test # temp commented out while pipeline is developed
      - make container-release
      - docker save -o docker.tar container-release:local
artifacts:
  files:
    - docker.tar
